### ISSUE TITLE
Does this work with Windows?

### ISSUE THREAD

**Issue by ThePython10110** [keijokapp/score-util#1]
I decided that I wanted to find some way to make video scores, and found this 10 hours after it was released.
It doesn't seem like it works with Windows, since it tries to run `mscore` (which doesn't exist on Windows). I created a file called `mscore.cmd`, with this command in it (which effectively runs MuseScore with any arguments given to it):
```
"C:\Program Files\MuseScore 4\bin\Musescore4.exe" %*
```
I added it to the path, and it still didn't work. This command:
```
create-musescore-video C:\Portable\Musescore\musescore4\hff\Footprint.mscz test.mp4
```
Gives this output:
```
Loading score media for C:\Portable\Musescore\musescore4\hff\Footprint.mscz
Failed to get score media {
  file: 'C:\\Portable\\Musescore\\musescore4\\hff\\Footprint.mscz',
  stdout: '',
  stderr: '',
  e: 'spawn mscore ENOENT'
}
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawn mscore ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn mscore',
  path: 'mscore',
  spawnargs: [
    '--score-media',
    'C:\\Portable\\Musescore\\musescore4\\hff\\Footprint.mscz'
  ],
  cmd: 'mscore --score-media C:\\Portable\\Musescore\\musescore4\\hff\\Footprint.mscz'
}
```

`create-musescore-video Footprint.mscz, output.mp4` (obviously in the same directory as `Footprint.mscz`) has the same result.

`mscore --score-media C:\\Portable\\Musescore\\musescore4\\hff\\Footprint.mscz` prints nothing, but doesn't give an error. Same with
```
C:\Program` Files\MuseScore` 4\bin\MuseScore4.exe --score-media C:\Portable\MuseScore\MuseScore4\HFF\Footprint.mscz
```

I also tested this with MuseScore 3 (everything acts exactly the same).

**Comment by keijokapp** [comment]
Thanks for the issue. I pretty much forgot about Windows users.

The following link thread gives an insight about the empty output: https://musescore.org/en/node/331599

> There's no stdout (in Qt-based apps) on Windows, that's probably why. Run it in a debugger to see the output.

I will research possible workarounds for that. I guess the simplest and the most obvious one would be to use temporary file output instead of stdout. But I really hate doing disk IO for what should be IPC.

A temporary workaround for you would be to extend your script with `-o some-tmp-file.json && type some-tmp-file.json`

**Comment by ThePython10110** [comment]
```
"C:\Program Files\MuseScore 4\bin\Musescore4.exe" %* -o C:\Portable\MuseScore\tmp.json && type C:\Portable\MuseScore\tmp.json
```
When I use this (`mscore --score-media Footprint.mscz`), the JSON file is created and printed as expected, but when running `create-musescore-video Footprint.mscz test.mp4` (even if I use absolute paths), it gives the same error as before.
